name: Submit a pull request for release

on:
  issues:
    types:
      - opened
      - edited
      - reopened
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Process
        run: |
          echo "CALENDER_CONTENT=calender_content" >> $GITHUB_ENV
    outputs:
      CALENDER_CONTENT: ${{ env.CALENDER_CONTENT }}

  submit:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.CALENDER_CONTENT }}
    env:
      CALENDER_CONTENT: ${{ needs.build.outputs.CALENDER_CONTENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Save to file
        run: echo "${{ env.CALENDER_CONTENT }}" > calender.ios
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        id: comment
        with:
          issue-number: 1
          body: |
            Calender result:
            ${{ env.CALENDER_CONTENT }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          title: Pull request by create-pull-request action
          body: |
            check out: #${{ github.event.number }}
      - name: Check outputs
        run: |
          echo "Comment ID - ${{ steps.comment.outputs.comment-id }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
