name: Submit a pull request for release

on:
  issues:
    types:
      - opened
      - edited
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Process
        run: |
          {
            echo 'CALENDER_CONTENT<<EOF'
            python calender.py ${{ github.event.issue.body }}
            echo EOF
          } >> "$GITHUB_ENV"
    outputs:
      CALENDER_CONTENT: ${{ env.CALENDER_CONTENT }}

  submit:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.CALENDER_CONTENT }}
    env:
      CALENDER_CONTENT: ${{ needs.build.outputs.CALENDER_CONTENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Save to file
        run: |
          echo "${{ env.CALENDER_CONTENT }}" > calender.ics
      - name: Find comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Content generated successfully!
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            **Content generated successfully!** :tada:
            <details>
            <summary>Calender content</summary>
            ${{ env.CALENDER_CONTENT }}
            </details>
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          labels: |
            triggered
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          commit-message: Update calender content
          title: Update calender content
          body: |
            fix: #${{ github.event.issue.number }}

            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
      - name: Check outputs
        run: |
          echo "Comment ID - ${{ steps.comment.outputs.comment-id }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
