name: Submit a pull request for release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/submit-pr.yml'
      - 'config/sat.yml'
      - 'bin/ci.py'
      - 'hwsat/calender.py'

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Check inputs
        run: |
          {
            echo 'CALENDER_CONFIG<<EOF'
            cat config/sat.yml
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Process
        run: |
          python bin/ci.py
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          labels: |
            triggered
          assignees: ${{ github.repository_owner }}
          reviewers: ${{ github.repository_owner }}
          commit-message: 'feat: generate calendar subscription for ${{ env.CALENDER_YEAR }}'
          title: '[Bot] generate calendar subscription for ${{ env.CALENDER_YEAR }}'
          body: |
            input:
            ```yaml
            ${{ env.CALENDER_CONFIG }}
            ```
      - name: Check outputs
        run: |
          echo "Comment ID - ${{ steps.comment.outputs.comment-id }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
